---
- name: "pull image"
  docker_image: name={{ item }}
  with_items:
    - jenkins

- name: run jenkins container
  docker_container:
    name: my_jenkins
    image: jenkins
    volumes:
        - "/var/my_jenkins_home:/var/jenkins_home"
    ports:
        - "8083:8080"
        - "5000:5000"
